### ISSUE TITLE
Bluetooth syncing

### ISSUE THREAD

**Issue by joshuagruenstein** [frc5806/ScoutingApp#15]
We have no assurance of cell communication at either the Armory or RIT, and especially if we use tablets, we need to be able to sync devices over Bluetooth.

**Comment by truell20** [comment]
This worries me a little bit. Can we make sure we can't do hot spots and there will be no wifi.

**Comment by truell20** [comment]
Bradley points out that the armory normally allows wifi: http://www.armory.nyc/wifi-access/

**Comment by joshuagruenstein** [comment]
They'll definitely turn off wifi, as it interferes with the control system.  That is what they do at other regionals.  The question is whether there'll be cell reception, but even if there is, that won't help us if we're using tablets.

**Comment by truell20** [comment]
If tablets were the only reason to go for bluetooth syncing, we'd just make it work with phones.

**Comment by joshuagruenstein** [comment]
Is bluetooth syncing really that hard?  I feel like, especially with a singular base station that every tablet syncs to, ionic should make it fairly easy.

**Comment by Bradley21890543** [comment]
Bluetooth is platform dependent so it might be more difficult with ionic.

**Comment by truell20** [comment]
It's not trivial. Bluetooth with ionic is very fucky since it tries to be device agnostic.

**Comment by Bradley21890543** [comment]
Why don't we rewrite the app in Swift & Java so we can use the native APIs?

**Comment by joshuagruenstein** [comment]
I'm just worried we'll get to a regional, not have cellular reception, and be screwed.  What if we supported syncing with a base station via USB?  After scouting,  everybody syncs with the computer to offload their data, then again to get all the data on everybody's devices.   It's obviously not ideal, but it saves us in case we have an issue with cellular.

**Comment by Bradley21890543** [comment]
I don't think that is possible with ionic.

**Comment by joshuagruenstein** [comment]
@Bradley21890543 Unless we have members of P&E who are already very familiar with native android and IOS dev, and willing to put in a lot of time, I think ionic makes more sense.  Especially considering how much functionality we'd like to add.

**Comment by truell20** [comment]
There's also odd edge cases with merging data. With a scouting team as large as ours, it's not inconcievable that two people write down conflicting scouting info about a team.

**Comment by joshuagruenstein** [comment]
Don't we already have that issue with our current model?

**Comment by truell20** [comment]
Also, y would cell reception go away. Can't we just check if its available before making a decision.

**Comment by joshuagruenstein** [comment]
That's probably a good idea.  Do we have team members that have been to the Armory who we can ask?  For RIT we should be able to ask Jason Levy.

**Comment by truell20** [comment]
@joshuagruenstein Since you can immediately sync, we don't really have that problem. People know what scouting info we have at all times, and so know what they're overwriting when they make a change to existing info.

With the USB model, everyone's in the dark.

**Comment by Bradley21890543** [comment]
This doesn't look sooooo bad: https://ionicframework.com/docs/v2/native/ble/

**Comment by truell20** [comment]
Their bluetooth frameworks aren't great. I've played with them before. Main problem is getting Android and iPhone to play nice together. They have a different set of features.

**Comment by joshuagruenstein** [comment]
Bradley's link is for Ionic V2 tho, which I doubt you've played around with.  Might make sense to port our app to ionic v2 anyway.

**Comment by truell20** [comment]
@joshuagruenstein We have runners who have been to the armory track, like @rashkovert.

**Comment by truell20** [comment]
Ionic V2 probably won't make a difference for the problems with iOS and Android if the native device feature sets are different. Maybe I'm wrong.

**Comment by joshuagruenstein** [comment]
Might we want to switch anyway, just to be more future proof, especially considering the current app is so simple?

**Comment by truell20** [comment]
Sure. I was talking about adding bluetooth not switching the app over to v2.

**Comment by joshuagruenstein** [comment]
Yeah, this is a separate issue.  Just opened #16.
